### ISSUE TITLE
Allow for multiple viewers from different computers

### ISSUE THREAD

**Issue by geniusled** [Emerson1337/obs-browser-preview#2] opened 2024-04-12 16:12 UTC
Hello, i found your project convient and it seems to do what i was looking for.

i am trying to make the web page accessible by multiple users and i am having some issues.

the first viewer it will work,
the second viewer it might work.
if the first viewer refreshes, then the npm crashes.

`/Documents/obs-browser-preview/node_modules/obs-websocket-js/dist/msgpack.modern.js:456
      throw new Error('Socket not identified');
            ^
`

in the browser console it says:
`
 WebSocket is already in CLOSING or CLOSED state.    (index):23
`

Any suggestions as to what might be causing this?

**Comment by Emerson1337** [comment] 2024-06-27 00:44
If I didn't miss understand this is an issue happening on the obs-websocket-js library. This might be due to a race condition causing some conflicts when connecting. 

Look this piece of code:

![image](https://github.com/Emerson1337/obs-browser-preview/assets/58860863/0c57bae9-c993-490d-b5bb-249b5086a3a7)

It means, if you increase the refresh time, it will be harder to throw this error `/Documents/obs-browser-preview/node_modules/obs-websocket-js/dist/msgpack.modern.js:456 throw new Error('Socket not identified'); ^`.

I didn't think in any way to avoid this. 

Other than that, I could mitigate some issues caused by this multiple users. Check the latest changes.

As a workaround, by decreasing the FPS to 30 and adding up some delay before connecting to OBS Websocket I couldn't replicate the issue here.

**Comment by Emerson1337** [comment] 2024-06-27 00:45
Will close this issue but feel free to open again if any idea come up.

**Comment by Emerson1337** [comment] 2024-06-27 00:45
Will close this issue but feel free to open it again if any idea come up. Thanks for using my idea! 🚀

**Closed as completed by Emerson1337** 2024-06-27 00:45 UTC
